### ISSUE TITLE
`copy()` creates an empty file called `r+.snirf`

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [BUNPC/pysnirf2#38]
Minimal code to demonstrate problem:

```python
from snirf import Snirf

with Snirf("test.snirf") as test:
    test.copy()
```

This produces 2 files: `test.snirf` as expected, and `r+.snirf`, which should not be created.

snirf 0.7.4
python 3.11.4
windows 11

Update: `r+.snirf` is created in the current working directory, no matter the path of the original file.

**Comment by sstucker** [comment]
Thanks--be advised copy functions were the latest addition to this package and may have other issues that are yet to surface. I recall they required a lot of HDF-fu

This is caused by a simple misuse of the the Snirf constructor in the copy method. I can release a fixed version soon, although if you are making use of the copy systems I urge you to contribute directly in the future as other fixes may be needed

**Comment by zEdS15B3GCwq** [comment]
Good to know, I'll probably avoid using `copy()` for now. Thanks for the quick response.
